package coser.gui.dialog.tcdser;

import java.awt.*;
import java.awt.event.*;
import coser.algorithm.*;

import coser.gui.guicommon.*;
import coser.gui.others.*;
import coser.gui.dialog.common.*;

/**
 * Project: The cost-sensitive rough sets project.
 * <p>
 * Summary: Compare the performances of the backtrack algorithm and heuristic
 * algorithm. The algorithm is implemented in
 * coser.datamodel.decisionsystem.TestCostSensitiveDecisionSystem.
 * <p>
 * Author: <b>Fan Min</b> minfanphd@163.com <br>
 * Copyright: The source code and all documents are open and free. PLEASE keep
 * this header while revising the program. <br>
 * Organization: <a href=http://grc.fjzs.edu.cn/>Lab of Granular Computing</a>,
 * Zhangzhou Normal University, Fujian 363000, China.<br>
 * Progress: Done.<br>
 * Written time: August 23, 2011. <br>
 * Last modify time: August 23, 2011.
 */
public class ErrorRangeTimeComparisonDialog extends Dialog implements
		ActionListener {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8811921637095529880L;

	public static ErrorRangeTimeComparisonDialog errorRangeTimeComparisonDialog = new ErrorRangeTimeComparisonDialog();

	/**
	 * Labmda.
	 */
	private DoubleField lambdaField;

	/**
	 * Number of experiments with different test-cost settings.
	 */
	private IntegerField experimentTimesField;

	/**
	 *************************** 
	 * The only constructor.
	 *************************** 
	 */
	private ErrorRangeTimeComparisonDialog() {
		// This dialog is not module
		super(GUICommon.mainFrame, "Time comparison", true);

		lambdaField = new DoubleField("-1", 10);
		experimentTimesField = new IntegerField("100", 10);

		Panel centerPanel = new Panel();
		centerPanel.setLayout(new GridLayout(2, 2));
		centerPanel.add(new Label("Lambda: "));
		centerPanel.add(lambdaField);
		centerPanel.add(new Label("Number of experiments: "));
		centerPanel.add(experimentTimesField);

		Button okButton = new Button(" Compute ");
		okButton.addActionListener(this);
		DialogCloser dialogCloser = new DialogCloser(this);
		Button cancelButton = new Button(" Cancel ");
		cancelButton.addActionListener(dialogCloser);
		Button helpButton = new Button(" Help ");
		helpButton.setSize(20, 10);
		helpButton
				.addActionListener(new HelpDialog(
						"Time comparison for backtrack and heuristic algorithms",
						"coser/gui/dialog/tcdser/ErrorRangeTimeComparisonDialogHelp.txt"));
		Panel okPanel = new Panel();
		okPanel.add(okButton);
		okPanel.add(cancelButton);
		okPanel.add(helpButton);

		setLayout(new BorderLayout());
		add(BorderLayout.CENTER, centerPanel);
		add(BorderLayout.SOUTH, okPanel);

		setBackground(GUICommon.MY_COLOR);
		setLocation(200, 150);
		setSize(350, 200);
		addWindowListener(dialogCloser);
		setVisible(false);
	}// Of constructor

	/**
	 *************************** 
	 * Read the arff file.
	 *************************** 
	 */
	public void actionPerformed(ActionEvent ae) {
		setVisible(false);
		ProgressDialog.progressDialog
				.setMessageAndShow("Please wait for a while."
						+ "\r\nThe execution time depends on the dataset size and the number of experiments."
						+ "\r\nThe progress is shown in the console.\r\n");

		try {
			// Use another name to make statements shorter.
			// TestCostDecisionSystemErrorRange currentSystem =
			// CoserProject.currentProject.currentTcNdsEr;

			// String message = "";

			double lambda = lambdaField.getValue();
			int experiments = experimentTimesField.getValue();
			String message = "";

			message = Reduction.batchComparisonErrorRange(lambda, experiments);

			message = "Generated by Coser http://grc.fjzs.edu.cn/~fmin, minfanphd@163.com\r\n"
					+ message;
			ProgressDialog.progressDialog.setMessageAndShow(message);
			// System.out.println(tempDecisionSystem);
		} catch (Exception ee) {
			ErrorDialog.errorDialog.setMessageAndShow(ee.toString());
			ProgressDialog.progressDialog.setVisible(false);
			return;
		}// Of try
			// ProgressDialog.progressDialog.setVisible(false);
	}// Of actionPerformed

}// Of class ErrorRangeTimeComparisonDialog

